outputFormat: json
analysisSampleRate: 44100
startTime: 0
endTime: 180.0
highlevel:
  compute: 1
  svm_models: [
            'models/mood_acoustic.history',
            'models/mood_aggressive.history',
            'models/mood_electronic.history',
            'models/mood_happy.history',
            'models/mood_party.history',
            'models/mood_relaxed.history',
            'models/mood_sad.history',
            ]
